name: test-manylinux

on:
  push:

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        include:
          - python-version: '3.6'
            py-short: '36'
            py-short2: '36m'
          - python-version: '3.7'
            py-short: '37'
            py-short2: '37m'
          - python-version: '3.8'
            py-short: '38'
            py-short2: '38'
          - python-version: '3.9'
            py-short: '39'
            py-short2: '39'
          - python-version: '3.10'
            py-short: '310'
            py-short2: '310'
    env:
      PYTHON: /opt/python/cp${{ matrix.py-short }}-cp${{ matrix.py-short2 }}/bin/python
    steps:
    - uses: actions/checkout@v1
    - run: docker build -t fugashi .
    - name: setup and test
      run: docker run -v $(pwd):/workdir -w /workdir fugashi sh -c "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/ && $PYTHON -m pip install cython pytest wheel unidic-lite ipadic && $PYTHON -m pip install -e . && $PYTHON -m pytest"
